version: '3.4'

services:
  prometheus:
    image: prometheus
    build:
      context: .
      dockerfile: Prometheus/dockerfile
    ports:
      - 9090:9090  
  webappmetrics:
    image: webappmetrics
    build:
      context: .
      dockerfile: WebAppMetrics/Dockerfile
    ports:
      - 5000:80
      - 443